version: 2

models:
  - name: fct_trips
    columns:
      - name: payment_type
        data_tests:
          - accepted_values:
              values: [1, 2, 3, 4, 5]
              quote: false
      - name: trip_id
        data_tests:
          - unique
          - not_null