taxi_rides_ny:
  target: dev
  outputs:
    # DuckDB Development profile
    dev:
      type: duckdb
      path: /app/taxi_rides_ny/taxi_rides_ny.duckdb
      schema: dev
      threads: 1
      settings:
        memory_limit: '4GB'
        preserve_insertion_order: false

    # DuckDB Production profile
    prod:
      type: duckdb
      path: /app/taxi_rides_ny/taxi_rides_ny.duckdb
      schema: prod
      threads: 1
      settings:
        memory_limit: '4GB'
        preserve_insertion_order: false

# Docker-specific notes:
# - Paths are relative to the container's filesystem
# - The database file is persisted via Docker volume
# - Adjust memory_limit based on Docker resource allocation
# - For Docker Desktop: ensure you've allocated at least 4GB RAM to Docker